### ISSUE TITLE
oidc-client-secret in kubeconfig.yaml, how secure is it?

### ISSUE THREAD

**Issue by ktzsolt** [int128/kubelogin#1088]
## Describe the question
I have set up kubelogin with (onprem) gitlab, all is working fine, I get this in my kubeconfig.yaml:
```yaml
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://mygitlab.com
      - --oidc-client-id=...
      - --oidc-client-secret=....
      - --oidc-extra-scope=email
```
The set up procedure says that I can share this kubeconfig with my team, and it works fine with rolebindings as it is supposed. 

I have set scopes only for openid, profile, email:
![kép](https://github.com/int128/kubelogin/assets/57558440/7dd1a7ca-d365-4a1e-9228-70efe851c144)

My question is how secure is it to share this kubeconfig file that includes the `oidc-client-id` and `oidc-client-secret`. If the secret gets compromised (e.g.: pushed to a public repo ) can it be used to do harm in any way?

Thank you!

## Your environment
- OS: ubuntu
- kubelogin version:  v1.28.0
- kubectl version: v1.26.3
- OpenID Connect provider: gitlab (self hosted)
