### ISSUE TITLE
Standalone mode doesn't write refresh-token into kubeconfig

### ISSUE THREAD

**Issue by stralex7** [int128/kubelogin#1133]
## No refresh-token is written into ~/.kube/config
After successfully completing the flow

## To reproduce
~/..kube/config
```
- name: dex
  user:
    auth-provider:
      config:
        client-id: 
        client-secret: 
        extra-scopes: profile,email,groups
        idp-issuer-url: https://dex.local.net
      name: oidc
```
run kubelogin and complete authentication 
```
You got a valid token until 2024-09-02 18:33:09 +0200 CEST
I0902 17:33:30.200351   36397 standalone.go:112] writing the ID token and refresh token to /home/user/.kube/config
```
No refresh-token is written into the file, only id
## Your environment
- OS: ubuntu 18.04.6
- kubelogin version: e.g. v1.19
- kubectl version: v1.29.0 (go1.23.0 linux_amd64)
- OpenID Connect provider: DEX/OpenLDAP
