### ISSUE TITLE
Does kubelogin support group claim for RBAC authZ?

### ISSUE THREAD

**Issue by deanmax** [int128/kubelogin#1136]
## Describe the question
Documentation seems to indicate only `sub` claim returned in the token is accepted as Kube User in RBAC. I wonder if there's a way to do it as a group if we want to grant multiple user the same RBAC permission?

## To reproduce
Not a defect.

## Your environment
- OS: macOS Sonoma 14.3.1
- kubelogin version:v1.28.0
- kubectl version: e.g. v1.29.1
- OpenID Connect provider: Custom

**Comment by ronaldmiranda** [comment]
it would be interesting

**Comment by ronaldmiranda** [comment]
the creation of the suggested rolebinding is not needed.

just keep your kubeconfig configured like this:
```yaml
  - name: oidc
    user:
        exec:
            apiVersion: client.authentication.k8s.io/v1beta1
            args:
              - oidc-login
              - get-token
              - --oidc-issuer-url=https://xxxxxxxxx
              - --oidc-client-id=xxxxxxxx
              - --oidc-client-secret=xxxxxxxx
              - --oidc-extra-scope=email
              - --oidc-extra-scope=groups
            command: kubectl
            env: null
            interactiveMode: IfAvailable
            provideClusterInfo: false
```

your ClusterRoleBinding should look like this:

```yaml
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: Ronald-s-Homelab:devops
```
