### ISSUE TITLE
Run as a client-go credential plugin

### ISSUE THREAD

**Issue by int128** [int128/kubelogin#116]
Use https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins for transparently login feature, instead of wrapping kubectl.

Create a kubeconfig like:

```yaml
users:
- name: keycloak
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubelogin
      args:
      - get-token
```

kubectl will execute `kubelogin get-token` before API calls. The command should return a token like the following json via standard output.

```json
{
  "apiVersion": "client.authentication.k8s.io/v1beta1",
  "kind": "ExecCredential",
  "status": {
    "token": "YOUR_ID_TOKEN",
  }
}
```
