### ISSUE TITLE
client-go credential plugin is slow compared to running as a command

### ISSUE THREAD

**Issue by aperullo** [int128/kubelogin#122]
Using kubelogin in client-go mode is very slow when compared to simply using the `kubelogin` command to generate the kubeconfig.

Consider 2 users:

```
- name: grunt
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://<URL>/auth/realms/master
      - --oidc-client-id=kubernetes
      - --oidc-client-secret=<SECRET>
      - --certificate-authority=./kube-ca.pem
      command: kubectl
      env: null
- name: grunt-manual
  user:
    auth-provider:
      config:
        client-id: kubernetes
        client-secret: <SECRET>
        extra-scopes: groups
        id-token: <ID_TOKEN>
        idp-certificate-authority: ./kube-ca.pem
        idp-issuer-url: https:/<URL>/auth/realms/master
        refresh-token: <REFRESH_TOKEN>
      name: oidc
```

grunt:
```
> time (kcl get pods)
Open http://localhost:18000 for authentication
[17173:17192:0729/164900.154984:ERROR:browser_process_sub_thread.cc(221)] Waited 3 ms for network service
You got a valid token until 2019-07-29 16:50:00 -0400 EDT
Unable to connect to the server: getting credentials: decoding stdout: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
( kubectl get pods; )  0.12s user 0.05s system 5% cpu 3.297 total

> time (kcl get pods)
No resources found.
( kubectl get pods; )  0.14s user 0.03s system 7% cpu 2.173 total

...after token expires and refresh token is needed

> time (kcl get pods)
Open http://localhost:18000 for authentication
[20058:20085:0729/165124.847344:ERROR:browser_process_sub_thread.cc(221)] Waited 9 ms for network service
You got a valid token until 2019-07-29 16:52:25 -0400 EDT
Unable to connect to the server: getting credentials: decoding stdout: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
( kubectl get pods; )  0.18s user 0.01s system 6% cpu 2.999 total
```

grunt-manual:
```
> kubelogin --user -grunt-manual --certificate-authority kube-ca.pem
Open http://localhost:18000 for authentication
[14214:14242:0729/164628.365946:ERROR:browser_process_sub_thread.cc(221)] Waited 3 ms for network service
Opening in existing browser session.
You got a valid token until 2019-07-29 16:47:29 -0400 EDT

> time (kcl get pods)
No resources found.
( kubectl get pods; )  0.06s user 0.02s system 9% cpu 0.828 total

...after token expires and refresh token is needed

> time (kcl get pods)
No resources found.
( kubectl get pods; )  0.12s user 0.02s system 12% cpu 1.047 total
```

## TL;DR
Time to issue a command.

| Command | Time without refresh (s) | Time with refresh (s) |
| --- | --- | --- |
| grunt | 2.173s | 2.999s |
| grunt-manual | 0.828s | 1.047s |
| **how much slower?** | **162%** | **186%** |
