### ISSUE TITLE
Additional Scopes Missing from Retrieved Token

### ISSUE THREAD

**Issue by aetherith** [int128/kubelogin#1355]
## Describe the issue
When requesting additional claims from Authelia as OIDC provider the returned JWT does not include the requested claims.

## To reproduce
Authelia client configuration:

```yaml
 - client_name: Kubernetes
   client_id: kubernetes
   client_secret: $pbkdf2-sha512$310000$VALID_HASH
   public: false
   authorization_policy: 'one_factor'
   redirect_uris:
     - 'http://localhost:8000'
     - 'http://localhost:18000'
   grant_types:
     - 'refresh_token'
     - 'authorization_code'
   scopes:
     - 'openid'
     - 'profile'
     - 'groups'
     - 'email'
```

Kubelogin setup command:

```bash
kubectl oidc-login setup  \
  --oidc-issuer-url=https://authelia.example.com \
  --oidc-client-id=kubernetes \
  --oidc-client-secret=VALID_SECRET \
  --oidc-extra-scope="openid profile groups email"
```

Command Response

```json
{
  "amr": [
    "pwd",
    "kba"
  ],
  "at_hash": "****",
  "aud": [
    "kubernetes"
  ],
  "auth_time": 1749667840,
  "azp": "kubernetes",
  "exp": 1749671444,
  "iat": 1749667844,
  "iss": "https://authelia.example.com",
  "jti": "****",
  "nonce": "****",
  "sub": "********-****-****-****-************"
}
```

## Expectation

The additional requested scopes would be returned as part of the token.

## Your environment
- OS: Fedora
- kubelogin version: 1.32.4
- kubectl version: 1.33.1
- OpenID Connect provider: Authelia

**Comment by aetherith** [comment]
It looks like this was a misconfiguration of Authelia on my side. Fairly recently they changed their flow so only the minimum set of claims was passed back as part of the ID token. They expect clients to then reach out to the UserInfo endpoint with the ID token to retrieve the full set of claims in the Authorization token. It seems like this plugin either doesn't do that or I couldn't figure out how to configure it to do so. The solution was to amend my Authelia client config as follows:

```yaml
identity_providers:
  oidc:
    claims_policies:
      default:
        id_token:
          - 'preferred_username'
          - 'groups'
    clients:
      - client_name: Kubernetes
        claims_policy: 'default'
```
