### ISSUE TITLE
Authentication with extra scope "email/profile" fails

### ISSUE THREAD

**Issue by TheRum** [int128/kubelogin#194]
Kind : Bug
Reference Issue/question : #156 

### Description :
When we try authenticating an user by email, we get `E1210 05:33:11.849924 1 authentication.go:89] Unable to authenticate the request due to an error: [invalid bearer token, oidc: parse username claims "email": claim not present]` error in the api-server logs. Issue here is, there is no 'email' details in the response token we receive from Google. On deep diving, I found that there is an issue with the requesting URI itself, which is not as expected by Google. And so the issue.

Current request URI has bad scope argument `scope=email+openid&` where as google expect it as `scope=openid%20email&` .

I tried by changing the scope value in the request URI and it worked as expected. I did get "email" details in the response token now.

### Possible Solution :
"--oidc-extra-scope" arguments are to be appended to "openid" properly, leaving whitespace between each word.

**Comment by int128** [comment]
Would you tell me how to reproduce this issue?

I have tried the following kubeconfig.

```yaml
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://accounts.google.com
      - --oidc-client-id=********.apps.googleusercontent.com
      - --oidc-client-secret=********
      - --oidc-extra-scope=email
      - -v1
      command: kubectl
      env: null
```

The scope of redirect URI seems `scope=email+openid` as you mentioned.

```
% curl -v localhost:8000
...
< HTTP/1.1 302 Found
< Content-Type: text/html; charset=utf-8
< Location: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&client_id=********.apps.googleusercontent.com&code_challenge=********&code_challenge_method=S256&nonce=********&redirect_uri=http%3A%2F%2Flocalhost%3A8000&response_type=code&scope=email+openid&state=********
```

I proceeded the authentication on Chrome and finally got the email claim from Google IdP as follows:

```
I1211 21:18:58.368396   98830 authcode.go:22] performing the authentication code flow
Open http://localhost:8000 for authentication
I1211 21:19:05.329595   98830 get_token.go:91] the ID token has the claim: email=********@gmail.com
```
