### ISSUE TITLE
Cannot add OIDC CA cert

### ISSUE THREAD

**Issue by elvinasp** [int128/kubelogin#20]
Kind: BUG

I suspect this might be a bug, but also might be some feature. :) I am using self signed CA to generate SSL certs and Kubelogin fails to add CA certificate from file for Keycloak auth service if it is defined the following way in the .kube\config:

UPDATE: Seems this is an issue only for Windows environment. kubelogin for Linux environments works as expected. 

```yaml
- name: cluster.local
  user:
    auth-provider:
      config:
        client-id: kubernetes
        client-secret: UUID
        id-token: ****
        idp-certificate-authority: C:\Users\Administrator\.kube\cluster.local.crt
        idp-issuer-url: https://keycloak.cust.lan/auth/realms/kubernetes
        refresh-token: ******
      name: oidc

```
Kubelogin throws the following error:
```
PS C:\Users\Administrator> kubelogin
2018/10/25 15:41:38 Reading ~/.kube/config
2018/10/25 15:41:38 Using current-context: cluster.local
2018/10/25 15:41:38 Error: Could not configure TLS: Could not append CA certificate from C:\Users\Administrator\.kube\cluster.local.crt
```

However if I define cert file the this way, then kubelogin works:
```
auth-provider-arg: idp-certificate-authority=C:\Users\Administrator\.kube\cluster.local.crt
```

Configuration file is generated via kubectl and I have not been successful to insert it to `.kube\config` in the above format. I would prefer not to edit _config_ file and have a way to script initial config. 

```
kubectl config set-credentials $CLUSTER_NAME `
  --auth-provider oidc `
  --auth-provider-arg idp-issuer-url=$KEYCLOAK_ADDRESS/auth/realms/kubernetes `
  --auth-provider-arg client-id=$CLIENT_ID `
  --auth-provider-arg idp-certificate-authority=$TARGETDIR\$CLUSTER_NAME.crt `
  --auth-provider-arg client-secret=$CLIENT_SECRET 
```
