### ISSUE TITLE
certificate-authority-data

### ISSUE THREAD

**Issue by flarno11** [int128/kubelogin#231]
In the `auth-provider` type there was the possibility to directly supply the base64 encoded CA certificate with `idp-certificate-authority-data`:
```
- name: olt-stage-oidc-old
  user:
    auth-provider:
      config:
        idp-certificate-authority-data: XXX
```

In the new `exec` type with `kubectl oidc-login get-token` I only see the option to pass it as a file with `--certificate-authority`:
```
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubectl
      args:
      - oidc-login
      - get-token
```

`--certificate-authority-data` nor `--auth-provider-arg idp-certificate-authority-data` seem to work. Is this feature missing or am I missing something?

Tested with v1.15.2 and v1.16.0
