### ISSUE TITLE
Cannot verify setup: Invalid client credentials

### ISSUE THREAD

**Issue by christianbeland** [int128/kubelogin#234]
I try to verify the setup but keep receiving this message. It is connecting with dex.

```
kubectl oidc-login setup --oidc-issuer-url=https://auth.k8s.local/   --oidc-client-id=client-id   --oidc-client-secret=client-secret
## 2. Verify authentication
Open http://localhost:8000 for authentication
Opening in existing browser session.
error: error: error while authentication: error while the authorization code flow: error while the authorization code flow: could not get a token: error while exchanging authorization code and token: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client","error_description":"Invalid client credentials."}
```

**Comment by christianbeland** [comment]
Once logged in, I get the OK page when the console prints that it cannot fetch token.

**Comment by int128** [comment]
> Invalid client credentials

Would you check the client ID and secret?

For example, if you are using the static clients like:

```yaml
staticClients:
  - id: YOUR_CLIENT_ID
    redirectURIs:
      - http://localhost:8000
    name: kubelogin
    secret: YOUR_CLIENT_SECRET
```

the command is like:

```
kubectl oidc-login setup --oidc-client-id=YOUR_CLIENT_ID --oidc-client-secret=YOUR_CLIENT_SECRET
```
