### ISSUE TITLE
Not able to login as different user or logout until token expires

### ISSUE THREAD

**Issue by elvinasp** [int128/kubelogin#29]
Kind: feature request

Description: When logged with OIDC based user, there are no direct  (user friendly) options to logout or login with another credentials. User has to wait until token expires or needs to open Keycloak console page to logout. 

Also for some time I was able to login with different user, but that stopped working with no obvious changes on both Kubernetes and client sides. After running kubelogin, browser automatically opens new tab and closes it. Kubelogin gets some (cached??) token value and kubectl remains happy with old credentials. If I run kubelogin with "/skip-open-browser" and open "http://localhost:8000" myself, I immediately get "OK" response, instead of login prompt. 

If I clear browsing history, then login prompt is presented as expected. 

OS: Windows 10, build: 1607
Browser: Chrome, Version 71.0.3578.98
Kubelogin: 1.8

Can browse be fed with some "no cache" options? Or was this behavior intentional?

**Comment by dimakow** [comment]
Another reason for a "no cache" or rather "clean-cache" parameter could be that the user groups have changed (more privileged) on IdP side for a given user and that user now wants to use the changed privileges without having to wait until the token expires.

**Comment by agaudreault-jive** [comment]
If you simply want to logout, you can clear the cache with `rm -r ~/.kube/cache/oidc-login` and this will re-trigger the authorization flow with your identity provider. Add an alias if it is something that you often need to do.

In the case you have multiple users, you probably want to define 2 users in your kubeconfig and add the `login_hint` parameter with `--oidc-auth-request-extra-params=login_hint=username@company.com`

**Comment by brightzheng100** [comment]
I still couldn't figure out how to have more than one user logged in, even I've applied the `login_hint`, like what I did here:

```yaml
- name: oidc-admin1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=<REDACTED>
      - --oidc-redirect-url-hostname=<REDACTED>
      - --oidc-client-id=<REDACTED>
      - --oidc-client-secret=<REDACTED>
      - --oidc-extra-scope=email
      - --oidc-auth-request-extra-params=login_hint=admin1@example.org
      - --certificate-authority=/tmp/ca.pem
      command: kubectl
      env: null
      provideClusterInfo: false
- name: oidc-developer1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=<REDACTED>
      - --oidc-redirect-url-hostname=<REDACTED>
      - --oidc-client-id=<REDACTED>
      - --oidc-client-secret=<REDACTED>
      - --oidc-extra-scope=email
      - --oidc-auth-request-extra-params=login_hint=developer1@example.org
      - --certificate-authority=/tmp/ca.pem
      command: kubectl
      env: null
      provideClusterInfo: false
```

If I've logged into K8s as `admin1@example.org` which has been granted `cluster-admin`:
```sh
$ kubectl --user=oidc-admin1 get nodes
NAME                             STATUS   ROLES                  AGE    VERSION
kind-control-plane   Ready    control-plane,master   6h2m   v1.21.1
kind-worker          Ready    <none>                 6h2m   v1.21.1
```

And then I'd try the `developer1@example.org`, who hasn't been bound to any role/clusterrole, but the result would be the same, without another prompt for the login process:
```sh
$ kubectl --user=oidc-developer1 get nodes
NAME                             STATUS   ROLES                  AGE    VERSION
kind-control-plane   Ready    control-plane,master   6h5m   v1.21.1
kind-worker          Ready    <none>                 6h4m   v1.21.1
```
