### ISSUE TITLE
Feature request: Custom page on successful login

### ISSUE THREAD

**Issue by bartlettc22** [int128/kubelogin#307]
Would like to see an option for adding custom HTML for the successful login page.  Right now it says 'OK' but would like the option to be a little more descriptive.

**Comment by int128** [comment]
Thank you for your contribution! This looks good. Would you tell me the message in your use case? I want to change the default message more helpful.

See also https://github.com/int128/kubelogin/issues/193#issuecomment-633554078.

**Comment by bartlettc22** [comment]
I would put something like `<p>Kubernetes login successful.  You can now close this page.</p>`

**Comment by bartlettc22** [comment]
I can update it in #308 if you like that wording

**Comment by int128** [comment]
Thank you for your PR. I think the custom option is overkill and it would be happy for every users to make the default page more descriptive. I just created #312 and please let me know if you have ideas.

**Comment by int128** [comment]
@sfxworks I'd like to confirm the purpose of https://github.com/int128/kubelogin/pull/308#issuecomment-654035887. Do you need this feature to show a custom page after authentication?

I think it would be nice if user can set a URL to be redirected after authentication, like:

```yaml
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://accounts.google.com
      - --oidc-client-id=YOUR_CLIENT_ID
      - --auth-success-url=https://your-site.example.com/login-success.html
      command: kubectl
```
