### ISSUE TITLE
Refresh token is empty string

### ISSUE THREAD

**Issue by Baykonur** [int128/kubelogin#36]
I have something similar to [this issue](https://github.com/int128/kubelogin/issues/11), the IdP we are using is AD FS 4.0 on Windows Server 2016. 

We get the token id but the refresh token is literally "".

We start the kube-apiserver with the following extra arguments:

```
apiServer:
  extraArgs:
    oidc-client-id: "<CLIENT ID>"
    oidc-issuer-url: "https://IDP ENDPOINT"
    oidc-username-claim: "upn"
    oidc-username-prefix: "-"
```
