### ISSUE TITLE
kubelogin server not running?

### ISSUE THREAD

**Issue by mecampbellsoup** [int128/kubelogin#451]
## Describe the issue

I have configured my `~/.kube/config` file to use kubelogin via an exec command, pointing it to my IdP:

```yaml
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://192.168.0.22:8001
      - --oidc-client-id=kubernetes
      - --oidc-client-secret=uGk8eEg3OaQIwaCUXbOd9dzOEUkdGNlq7ZjMmC2XtYBnDkU9
      - --certificate-authority=/Users/mattysoup/code/coreweave/gatekeeper/ssl/ca.pem
      command: kubectl
      env: null
```
My OIDC issuer is running on my host (i.e. machine's `localhost`, not some remote host) - it's a self-written Django OIDC auth server, FWIW.

## To reproduce

I ran `brew install kubelogin`, started my k8s API server and my local OIDC auth server.

I set the kubeconfig above.

Finally I run `k get pods --user oidc`. The following is displayed in the browser:

![image](https://user-images.githubusercontent.com/2043821/104762474-69cdac00-5732-11eb-9fe6-7ca0cf5150bb.png)

Where is the kubelogin server?!

## Your environment
- OS: macOS
- kubelogin version: `kubelogin version v1.22.0 (go1.15.3 darwin_amd64)`
- OpenID Connect provider: self-written Django application bound to `192.168.0.22:8001`
- kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
