### ISSUE TITLE
Tilde is not expanded in --token-cache-dir

### ISSUE THREAD

**Issue by Mattias-** [int128/kubelogin#488]
## Describe the issue
Tilde `~` is not expanded when specifying a directory with `--token-cache-dir` when running as a kubectl credential plugin (https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuration). In standalone mode this might be fine as a shell probably will expand it.

## To reproduce
Run `get-token` with kubeconfig:
```yaml
...
users:
- name: default-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubectl
      args:
      - oidc-login
      - get-token
      - --token-cache-dir=~/.kube/cache/oidc-login
...
```
or some other path that starts with `~`.
This will create a directory that literally is called `~` in the current working directory as it's not expanded.

## Your environment

- OS: Linux
- kubelogin version: v1.22.1
- kubectl version: v1.19.6
- OpenID Connect provider: Google
