### ISSUE TITLE
Add token to the kube config file for kubernetes dashboard

### ISSUE THREAD

**Issue by arcalys** [int128/kubelogin#53]
Hi,

Kubernetes dashboard does not support auth-provider when trying to log in with the config file instead of a token, it needs a token at the same level as the auth-provider under user, e.g.:

```
- name: username
  user:
    auth-provider:
      config:
        client-id: id
        client-secret: secret
        id-token: token
        idp-issuer-url: https://accounts.google.com
        refresh-token: xx
      name: oidc
    token: token
```

Would be nice if the generated token could be added as well in order for the kubeconfig file to be usable to log in as well.
