### ISSUE TITLE
This is not working for EKS

### ISSUE THREAD

**Issue by rpuserh** [int128/kubelogin#671]
Hi,
Im not able to make this work for EKS cluster
Followed all documentation.
When i try `kubectl get pods` it opens browser and I login 
Everything looks good no errors.
But when browser auth is done i see error in command line 
```
error: You must be logged in to the server (Unauthorized)
```

I check file `cat  /root/.kube/cache/oidc-login/*`
and it exists 
As it exists for every kubectl command i get same message 
```
error: You must be logged in to the server (Unauthorized)
```

Please advice.

## environment
- OS: Ubuntu
- kubelogin version: v1.25.0
- kubectl version: v1.22.4
- OpenID Connect provider: Google

**Comment by int128** [comment]
AFAIK, EKS does not support OIDC authentication.

**Comment by rpuserh** [comment]
@int128 
They do support it : https://aws.amazon.com/blogs/containers/introducing-oidc-identity-provider-authentication-amazon-eks/

**Comment by int128** [comment]
Thanks!

I think the message indicates that the cluster could not validate the token.
Please check an error log of the EKS control plane in CloudWatch Logs.

**Comment by jurgen-weber-deltatre** [comment]
Hi, we are trying to do the exact same thing

![image](https://user-images.githubusercontent.com/77422409/144551627-11a10adb-1a3a-4423-afc2-a47d910cd741.png)

**Comment by jurgen-weber-deltatre** [comment]
so, in reading the message I thought I would be cheeky, I changed my kube config command to use a bash script and in that script

> kubectl oidc-login get-token --oidc-issuer-url=https://keycloak.example.io/auth/realms/my-realm --oidc-client-id=kubectl-openid --oidc-client-secret=my-secret | sed 's/"token":"/"token":"k8s-aws-v1./'

So then the output is formatted correctly:

```
{
  "kind": "ExecCredential",
  "apiVersion": "client.authentication.k8s.io/v1beta1",
  "spec": {
    "interactive": false
  },
  "status": {
    "expirationTimestamp": "2021-12-05T22:33:25Z",
    "token": "k8s-aws-v1.eyJhbGciOiJSUzGZWFCbWdUNUpxVDZjIn0.eyJleHAiO4OC00YmM4LT..."
  }
}
```

We compared it to the output of the aws cli and it looks the same but now I received the error

```
time="2021-12-05T22:28:27Z" level=warning msg="access denied" client="127.0.0.1:33644" error="input token was not properly formatted: illegal base64 data at input byte 111" method=POST path=/authenticate
```

**Comment by jurgen-weber-deltatre** [comment]
ok, so in the end this actually does work with EKS. I just had to configure the things correctly. When I pulled apart my JWT I noticed the username is under the key 'preferred_username' (so I had to update my AWS config to reflect this). Once that was matching I could authenticate. I am using keycloak as my IDP; I then had to create a group mapper to add the groups my user is assigned to, to that same JWT payload.

(I found the clue for the mapper on this blog: https://itnext.io/protect-kubernetes-dashboard-with-openid-connect-104b9e75e39c)
```
Then create a mapper. It allows group based access control.
Name: groups
Mapper Type: Group Membership
Token Claim Name: groups
```

**Comment by geoffo-dev** [comment]
I am having a very similar issue... I manually setup the configuration initially which I got working (as described above with the groups mapper) - however since I tried to automate the deployment across a number of clusters using terraform, I am getting the `error: You must be logged in to the server (Unauthorized)` error.

As far as I can tell I have everything setup correctly:

Cluster OIDC

<img width="1264" alt="Screenshot 2022-01-28 at 13 42 48" src="https://user-images.githubusercontent.com/53539843/151557328-40db3d6d-d121-45cf-ba67-f38e09fd4d99.png">

Client

<img width="1187" alt="Screenshot 2022-01-28 at 13 45 03" src="https://user-images.githubusercontent.com/53539843/151557737-47f886b3-fc6f-4db8-bf47-1aad2c6952aa.png">

Mapper

<img width="922" alt="Screenshot 2022-01-28 at 13 47 32" src="https://user-images.githubusercontent.com/53539843/151557801-bc92286e-9e05-4242-855c-576e8582a820.png">

Role:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oidc-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader
subjects:
- kind: Group
  name: keycloak:dev-eks-admin
  apiGroup: rbac.authorization.k8s.io
```

kubeconfig

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxx
    server: https://xxxx.xxx.eu-west-2.eks.amazonaws.com
  name: default
contexts:
- context:
    cluster: default
    namespace: default
    user: oidc
  name: default
kind: Config
preferences: {}
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://keycloak.xxxx/auth/realms/xxxx
      - --oidc-client-id=xxxxx-dev-cluster
      - --oidc-client-secret=xxxxxxx
      command: kubectl
      env: null
      provideClusterInfo: false
```

Token (which seems to be ok)

```json
{
  "exp": 1643374130,
  "iat": 1643374070,
  "auth_time": 1643368773,
  "jti": "xxxxxxx",
  "iss": "https://keycloak.xxxxx/auth/realms/xxxxx",
  "aud": "xxxxx-dev-cluster",
  "sub": "xxxxxxx",
  "typ": "ID",
  "azp": "eks-ddap-dev-cluster",
  "nonce": "xxxx",
  "session_state": "d2227c27-ef1f-48a2-a1b8-dc5e9296ff04",
  "at_hash": "xxxxx",
  "acr": "0",
  "email_verified": true,
  "name": "John Doe",
  "groups": [
    "dev-eks-admin"
  ],
  "preferred_username": "john.doe",
  "given_name": "John",
  "family_name": "Doe",
  "email": "john.doe@example.com"
}
```

However I am still seeing the issues in the log around non-properly formatted strings... 

<img width="1277" alt="Screenshot 2022-01-28 at 13 50 32" src="https://user-images.githubusercontent.com/53539843/151558262-e1cb3b28-b805-47a5-9037-3ed36d4e39ad.png">

Is there something I am missing?
