### ISSUE TITLE
Groups are ignored while using kube-oidc-proxy with keycloak

### ISSUE THREAD

**Issue by N05h3ll** [int128/kubelogin#692]
I am using keycloak to authenticate with kubernetes using kube-oidc-proxy and oidc-login.
I have created a client in keycloak and a mapper with the following configuration.
```yaml
Protocol: openid-connect
Name: Groups
Mapper Type: Group Membership
Token Claim Name: groups
Full group path: OFF
Add to ID token: OFF
Add to access token: OFF
Add to userinfo: OFF
```
The kube-oidc-proxy is running with this configuration:
```yaml
command: ["kube-oidc-proxy"]
args:
  - "--secure-port=443"
  - "--tls-cert-file=/etc/oidc/tls/crt.pem"
  - "--tls-private-key-file=/etc/oidc/tls/key.pem"
  - "--oidc-client-id=$(OIDC_CLIENT_ID)"
  - "--oidc-issuer-url=$(OIDC_ISSUER_URL)"
  - "--oidc-username-claim=$(OIDC_USERNAME_CLAIM)"
  - "--oidc-signing-algs=$(OIDC_SIGNING_ALGS)"
  - "--oidc-username-prefix='oidcuser:'"
  - "--oidc-groups-claim=groups"
  - "--oidc-groups-prefix='oidcgroup:'"
  - "--v=10"
```
And the kube config has this configuration:
```yaml
apiVersion: v1
clusters:
- cluster:
    server: <KUBE_OIDC_PROXY_URL>
  name: default
contexts:
- context:
    cluster: default
    namespace: default
    user: oidc
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - -v10
      - --oidc-issuer-url=<ISSUER_URL>
      - --oidc-client-id=kube-oidc-proxy
      - --oidc-client-secret=<CLIENT_SECRET>
      - --oidc-extra-scope=email
      - --grant-type=authcode
      command: kubectl
      env: null
      provideClusterInfo: false
```
I can successfully get the user info with groups in the jwt token as shown below:
```json
 "name": "Test Uset",
  "groups": [
    "KubernetesAdmins"
  ],
  "preferred_username": "test-user",
  "given_name": "Test",
  "family_name": "Uset",
  "email": "testuser@test.com"
```
And i have created the following cluster role binding:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-admin-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidcgroup:KubernetesAdmins
```
But I still get forbidden error as follows:
```
Error from server (Forbidden): pods is forbidden: User "'oidcuser:'ecc4d1ac-68d7-4158-8a58-40b469776c07" cannot list resource "pods" in API group "" in the namespace "default"
```
Any ideas on how to solve this issue ??
Thanks in advance,,
## Your environment
- OS: e.g. linux
- kubelogin version: e.g. v1.25.1
- kubectl version: e.g. v1.23.4
- OpenID Connect provider: e.g. Keycloak
