### ISSUE TITLE
Intermittently receiving "error: You must be logged in to the server (Unauthorized)"

### ISSUE THREAD

**Issue by Timoses** [int128/kubelogin#754]
## Describe the issue

At times running a `kubectl` command (e.g. `kubectl get services`) fails with:
```
error: You must be logged in to the server (Unauthorized)
```

The kube-apiserver logs in those cases:
```
E0722 11:41:09.420668       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, oidc: verify token: oidc: token is expired (Token Expiry: 2022-07-22 11:40:27 +0000 UTC)]
```

This prevails for some seconds or minutes after which it works again.

## To reproduce
The user is configured like this in `~/.kube/config`:
```
users:
- name: user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://my-oidc-host.int/auth/realms/kubernetes
      - --oidc-client-id=kubernetes
      - --skip-open-browser
      - --grant-type=password
      command: kubectl
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

## Your environment
- OS: Fedora
- kubelogin version: v1.25.1
- kubectl version: v1.24.2
- OpenID Connect provider: Keycloak
