### ISSUE TITLE
Refresh Token Call Doesn't Request Scopes

### ISSUE THREAD

**Issue by NArnott** [int128/kubelogin#798]
## Describe the issue
I am using Okta as an IDP, and as such, request both groups and offline_access as additional scopes so I can get the groups included in the Token  (as our RBAC is based on groups within the token). This works the first time, and I get a valid token for the lifetime of that token. I also get a refresh token. However, once the initial token expires, and the refresh token grant is requested, the initial scopes used aren't passed in the refresh call and no groups are included in the newly minted token, effectively removing my access to K8s. 

Example kube config user:
```
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://my.idp.com
      - --oidc-client-id=myclientid
      - --oidc-extra-scope=groups
      - --oidc-extra-scope=profile
      - --oidc-extra-scope=offline_access
      command: kubectl
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

## Your environment
- OS: Windows 11
- kubelogin version: v1.18.4
- kubectl version: v1.23
- OpenID Connect provider: Okta
