### ISSUE TITLE
token is being requested with each kubectl commands

### ISSUE THREAD

**Issue by mevinod** [int128/kubelogin#807]
## Describe the question
I am using kubelogin for the oidc authentication with keycloak. Whenever I perform a `kubectl` request, it gets token each time and displays it on the console.

Is there a way to suppress the logs? or do I am missing something?

This is the log - 

```
`I0927 14:36:15.540861     325 authentication.go:74] checking expiration of the existing token
I0927 14:36:15.540931     325 authentication.go:83] you already have a valid token until 2022-09-27 14:38:37 +0530 IST
I0927 14:36:15.540984     325 get_token.go:102] you got a token: {
  "exp": 1664269717,
  "iat": 1664269417,
  "auth_time": 1664269077,
  "jti": "",
  "iss": "https://something.com/client",
  "aud": "lid",
  "sub": "",
  "typ": "ID",
  "azp": "lid",
  "nonce": "K_Qp-iLKHcI6ORl8UQc-",
  "session_state": "92300d94-587f-e9084f1370f2",
  "at_hash": "iLKHcI6ORl8UQc",
  "acr": "1",
  "sid": "92300d94-9084f1370f2",
  "email_verified": false,
  "roles": [
    "offline_access",
    "uma_authorization",
    "default-roles-id"
  ],
  "name": "username username",
  "groups": [
    "mygroup"
  ],
  "preferred_username": "username",
  "given_name": "username",
  "family_name": "username",
  "user": "username"
}`
```

This is the sample kubeconfig I am using
```
`apiVersion: v1
preferences: {}
kind: Config

clusters:
- cluster:
    server: https://something.amazonaws.com
    certificate-authority-data: ca-data
  name: eks-clustername

contexts:
- context:
    cluster: clustername
    user: ${username}
  name: aclustername

current-context: clustername

users:
- name: ${username}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubectl
      args:
      - oidc-login
      - get-token
      - -v1
      - --oidc-issuer-url=https://oidc.issuer.url
      - --oidc-client-id=client-id
      - --oidc-client-secret=secret`

```
## To reproduce
Run any kubectl command

## Your environment
- OS: e.g. macOS
- kubelogin version: v1.25.3
- kubectl version:  GitVersion:"v1.25.1
- OpenID Connect provider: keycloak
