### ISSUE TITLE
Browser Tab explosion with authentication requests

### ISSUE THREAD

**Issue by Vad1mo** [int128/kubelogin#904]
## Describe the question

Upfront, I have OIDC and Kubernetes working hand in hand. 
There is however a major annoyance, I am not certain how to get rid of.

<img width="1688" alt="Bildschirm­foto 2023-03-10 um 08 07 45" src="https://user-images.githubusercontent.com/1492007/224249131-211c7c8c-0ee4-4012-862b-2dbc08daeccc.png">

This is how my browser looks like after I left my laptop idling for 5 hours.
Each tab is an authentication request. 

Now I wonder, how to get rid of it or mitigate it so it doesn't happen that frequently.

## To reproduce
A console log or steps to reproduce the issue.

## Your environment
- OS: macOS
- kubelogin version: v1.26.0 (go1.19.4 darwin_amd64)
- kubectl version: v1.26
- OpenID Connect provider: Google

**Comment by bclodius** [comment]
Hey @Vad1mo we're trying to solve a similar problem and I'm curious if you came up with any mitigation or solution on your end?

**Comment by Vad1mo** [comment]
> Hey @Vad1mo we're trying to solve a similar problem and I'm curious if you came up with any mitigation or solution on your end?

Only solution is not using tools the access k8s in the background. E.g. Lens or IDE, vs code or IntelliJ..

**Comment by pamgluss-slack** [comment]
We're still running into this and killing VSCode every night for every developer is not realistic so I opened a feature request here: https://github.com/int128/kubelogin/issues/1330

**Comment by alee-x** [comment]
I worked around this by setting the `--authentication-timeout-sec` arg to 3600 so it only opens 1 tab per hour instead of 1 every 1-2 minutes.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: [redacted]
    server: [redacted]
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=[redacted]
      - --oidc-client-id=kubernetes
      - --oidc-client-secret=[redacted]
      - --authentication-timeout-sec=3600
      command: kubectl
      env: null
      provideClusterInfo: false
```
