### ISSUE TITLE
kubectl works with token from `oidc-login get-token` but does not work when this is automated

### ISSUE THREAD

**Issue by maaft** [int128/kubelogin#917]
## Describe the issue
When I use the "standard" oidc-login flow:
```yaml
users:
- name: cluster
  user:
    client-certificate-data: <redacted>
    client-key-data: <redacted>
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://sts.windows.net/<redacted>/
      - --oidc-client-id=<redacted>
      - --oidc-client-secret=<redacted>
      - --oidc-extra-scope=email roles
      command: kubectl
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
I get: `error: You must be logged in to the server (Unauthorized)`

When I retrieve the token manually with:
```
kubectl oidc-login get-token --oidc-issuer-url=https://sts.windows.net/<redacted>/ --oidc-client-id=<redacted> --oidc-client-secret=<redacted> --oidc-extra-scope="email roles"
```
and put the token manually in`.kube/config`:
```yaml
users:
- name: tokenuser
  user:
    token: <redacted>
```
my `kubectl` commands work as exptected.

Additional Info:
- I have multiple clusters in my config where I use the same auth flow (different client-id) and there I experience no issues
- I tripple checked oidc-data for "auto-login" and "manual token retrieval" and they are exactly the same

How can I debug this further?
