### ISSUE TITLE
Work with Dex instead of keycloak?

### ISSUE THREAD

**Issue by bryanalves** [int128/kubelogin#93]
I'm trying to switch from keycloak to dex, with a pretty simple dex configuration:

```
config:
  issuer: https://auth.my.domain
  storage:
    type: memory
  logger:
    level: debug
  staticClients:
    - id: kubernetes
      name: Kubelogin
      secret: kubernetes
      public: true
  enablePasswordDB: true
  staticPasswords:
    - email: me@example.com
      hash: [REDACTED]
      username: me
      userID: me
```

relevant `.kube/config`:

```
- name: dex
  user:
    auth-provider:
      config:
        client-id: kubernetes
        idp-issuer-url: https://auth.my.domain
      name: oidc
```

Upon using kubelogin with this setup, I get directed to the dex login page, I log in, get redirected to the `OK` page that kubelogin usually lands me at, but with the following log on CLI:

```
Open http://localhost:8000 for authentication
Opening in existing browser session.
[26416:26425:0602/232637.294657:ERROR:browser_process_sub_thread.cc(217)] Waited 5 ms for network service
Error: could not get a token from the OIDC provider: could not get a token: error while exchanging authorization code and token: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client","error_description":"Invalid client credentials."}
```

The `OK` page has `code` and `state` in the query string parameters.  Running kubelogin with -v gives some additional information:

```
23:27:45.543896 WARNING: log may contain your secrets such as token or password
23:27:45.545056 Using the authentication provider of the user dex
23:27:45.545062 A token will be written to /home/me/.kube/config
23:27:45.545193 GET /.well-known/openid-configuration HTTP/1.1
Host: auth.my.domain
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip

23:27:45.717122 HTTP/1.1 200 OK
Transfer-Encoding: chunked
Connection: keep-alive
Content-Type: application/json
Date: Mon, 03 Jun 2019 03:27:45 GMT
Server: nginx/1.15.8
Vary: Accept-Encoding

2c1
{
  "issuer": "https://auth.my.domain",
  "authorization_endpoint": "https://auth.my.domain/auth",
  "token_endpoint": "https://auth.my.domain/token",
  "jwks_uri": "https://auth.my.domain/keys",
  "response_types_supported": [
    "code"
  ],
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "groups",
    "profile",
    "offline_access"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic"
  ],
  "claims_supported": [
    "aud",
    "email",
    "email_verified",
    "exp",
    "iat",
    "iss",
    "locale",
    "name",
    "sub"
  ]
}
0

Open http://localhost:8000 for authentication
Opening in existing browser session.
[26784:26793:0602/232746.633016:ERROR:browser_process_sub_thread.cc(217)] Waited 7 ms for network service
23:28:12.807176 POST /token HTTP/1.1
Host: auth.my.domain
User-Agent: Go-http-client/1.1
Content-Length: 103
Authorization: Basic a3ViZXJuZXRlczo=
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

code=uov7muno5wvtruwjcsur6wj7g&grant_type=authorization_code&redirect_uri=http%3A%2F%2Flocalhost%3A8000
23:28:12.810014 HTTP/1.1 401 Unauthorized
Content-Length: 76
Connection: keep-alive
Content-Type: application/json
Date: Mon, 03 Jun 2019 03:28:12 GMT
Server: nginx/1.15.8

{"error":"invalid_client","error_description":"Invalid client credentials."}
23:28:12.810397 POST /token HTTP/1.1
Host: auth.my.domain
User-Agent: Go-http-client/1.1
Content-Length: 124
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

client_id=kubernetes&code=uov7muno5wvtruwjcsur6wj7g&grant_type=authorization_code&redirect_uri=http%3A%2F%2Flocalhost%3A8000
23:28:12.812987 HTTP/1.1 401 Unauthorized
Content-Length: 76
Connection: keep-alive
Content-Type: application/json
Date: Mon, 03 Jun 2019 03:28:12 GMT
Server: nginx/1.15.8

{"error":"invalid_client","error_description":"Invalid client credentials."}
Error: could not get a token from the OIDC provider: could not get a token: error while exchanging authorization code and token: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client","error_description":"Invalid client credentials."}
```

Is there something fundamentally different with how dex does OAuth that isn't compatible with kubelogin?
